// @vitest-environment node

import { createServer } from "node:http";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { afterEach, describe, expect, it } from "vitest";
import type { Browser, Page } from "puppeteer-core";

import { CompositionHf, WorkspaceFs } from "@vidcom/adapter";
import { startVidcomFoundation } from "@vidcom/cli";
import type { ContentHash, ProjectId, RelPath } from "@vidcom/contracts";
import { generateCaptions, getPreviewSettings, type AbsolutePath, type ProjectRef } from "@vidcom/core";

import { requireBrowser } from "../support/browser-harness";
import { createSequentialIdPort } from "../support/deterministic";
import { writeSampleProject } from "../support/sample-project";

/**
 * Preview and render must highlight the same word at the same moment (R6.14).
 *
 * Both documents here are built by the production builder from **one real
 * project at one revision**, whose captions were generated by the real use case
 * from real word timings — not two hand-written pages that could agree with each
 * other and disagree with the app.
 */

const projectId = "project_caption_parity" as ProjectId;
const roots: string[] = [];
const runtimes: Array<{ stop(): Promise<void> }> = [];

/** Before the first word, inside the second, and after the last one. */
const POINTS = [
  { label: "before", sceneSeconds: 0.1, expect: null },
  { label: "during", sceneSeconds: 0.65, expect: "hai" },
  { label: "after", sceneSeconds: 1.4, expect: null },
] as const;

const WORDS = [
  { text: "một", startSeconds: 0.2, endSeconds: 0.5 },
  { text: "hai", startSeconds: 0.5, endSeconds: 0.8 },
  { text: "ba", startSeconds: 0.8, endSeconds: 1.2 },
];

afterEach(async () => {
  for (const runtime of runtimes.splice(0)) await runtime.stop();
  await Promise.all(roots.splice(0).map((root) => rm(root, { recursive: true, force: true })));
});

/** Reads the active caption word the runtime is showing at one root timestamp. */
async function activeWordAt(page: Page, rootSeconds: number, fps: number): Promise<string | null> {
  return await page.evaluate(({ frame }: { frame: number }) => {
    window.postMessage({ source: "hf-preview", type: "timeline", fps: { numerator: 30, denominator: 1 } }, "*");
    window.postMessage({ source: "hf-preview", type: "state", frame }, "*");
    const active = document.querySelector(".caption .w.active");
    return active?.textContent ?? null;
  }, { frame: Math.round(rootSeconds * fps) });
}

describe("caption preview/render parity", () => {
  it("highlights the same word in both documents of one real project", async () => {
    const available = await requireBrowser();
    if (!available.run) {
      process.stdout.write(`${available.message}\n`);
      return;
    }
    const root = await mkdtemp(path.join(tmpdir(), "vidcom-caption-parity-"));
    roots.push(root);
    const workspaceRoot = path.join(root, "workspace");
    await mkdir(workspaceRoot);
    const project = await writeSampleProject(workspaceRoot, {
      slug: "caption-parity",
      id: projectId,
      duration: 6,
      withTimeline: true,
    });
    // One document, one scene, captions inside it: the scene is authored inline
    // so the caption block the use case writes is part of the root composition
    // both builders below produce.
    await writeFile(path.join(project.root, "index.html"), `<!doctype html>
<html>
  <head><meta charset="UTF-8" /></head>
  <body>
    <main
      data-composition-id="main"
      data-width="1920"
      data-height="1080"
      data-fps="30"
      data-duration="6"
      data-start="0"
    >
      <div class="clip" data-composition-id="scene-1" data-start="0" data-duration="6" data-track-index="1">
        <h1 id="headline">Parity</h1>
        <div class="captions"></div>
      </div>
    </main>
  </body>
</html>
`, "utf8");
    // Subtitles on, with a distinct active colour, so the runtime has something
    // visible to drive at all.
    await writeFile(path.join(project.root, "preview-settings.json"), `${JSON.stringify({
      ...JSON.parse(await readFile(path.join(project.root, "preview-settings.json"), "utf8")) as Record<string, unknown>,
      subtitles: { enabled: true, override: true, color: "#111111", activeColor: "#12AB34" },
    }, null, 2)}\n`, "utf8");

    // Narration with real word timings: the captions below are planned from
    // these, not written by hand.
    await mkdir(path.join(project.root, "narration"), { recursive: true });
    await writeFile(path.join(project.root, "narration", "scene-1.json"), `${JSON.stringify({
      sceneId: "scene-1",
      text: "một hai ba",
      voice: "parity-voice",
      status: "generated",
      audioPath: "narration/scene-1.wav",
      revision: 1,
      updatedAt: "2026-08-02T00:00:00.000Z",
      staleSince: null,
      cues: [{
        cueId: "cue-1",
        text: "một hai ba",
        voice: "parity-voice",
        offsetSeconds: 0,
        status: "generated",
        audioPath: "narration/scene-1.wav",
        staleSince: null,
        wordTimingSource: "engine",
        words: WORDS,
      }],
    }, null, 2)}\n`, "utf8");

    const foundation = await startVidcomFoundation({
      appDataRoot: path.join(root, "app-data"),
      workspaceRoot: workspaceRoot as AbsolutePath,
      holderId: "test:caption-parity",
      clock: { now: () => new Date("2026-08-18T12:00:00.000Z") },
      ids: createSequentialIdPort(),
    }, {
      async recoverJobs() {}, async startScheduler() {}, async startWatcher() {}, async openListener() { return null; },
    });
    runtimes.push(foundation);
    const { infrastructure, application } = foundation;

    const ref = await infrastructure.workspace.readProjectRef(projectId);
    expect(ref, "the parity project was not registered").not.toBeNull();
    const sceneFile = "index.html" as RelPath;
    const resolved = await infrastructure.workspace.resolve(ref!, sceneFile, "read-source");
    expect(resolved.ok).toBe(true);
    if (!resolved.ok) return;
    const sceneHash = await infrastructure.workspace.readHash(resolved.value);

    const captions = await generateCaptions({
      workspace: infrastructure.workspace,
      composition: infrastructure.composition,
      authority: application.writeDependencies.authority,
    } as unknown as Parameters<typeof generateCaptions>[0], {
      projectId,
      sceneId: "scene-1",
      expectedContentHash: sceneHash as ContentHash,
    }, "user");
    expect(captions.ok ? null : captions.error, "captions were not generated").toBe(null);
    if (!captions.ok) return;
    expect(captions.value.timingSource).toBe("engine");

    // One project, one revision: both documents are built from what is on disk
    // now, by the same builder the daemon uses.
    const settingsResult = await getPreviewSettings({
      workspace: infrastructure.workspace,
      composition: infrastructure.composition,
      journal: infrastructure.journal,
    } as unknown as Parameters<typeof getPreviewSettings>[0], projectId);
    expect(settingsResult.ok).toBe(true);
    if (!settingsResult.ok) return;
    const settings = settingsResult.value.previewSettings;
    const composition = new CompositionHf();
    const workspace = new WorkspaceFs(workspaceRoot as AbsolutePath);
    const target = (await workspace.listProjects()).find((candidate) => candidate.id === projectId) as ProjectRef;
    const documents = {
      preview: await composition.buildDocument(target, settings, {
        root: true, mode: "preview", projectRevision: 1, changeSeq: 1, fileBaseUrl: "/files/",
      }),
      render: await composition.buildDocument(target, settings, {
        root: true, mode: "render", fileBaseUrl: "/files/",
      }),
    };
    const evidence = path.join(root, "evidence");
    await mkdir(evidence, { recursive: true });
    for (const [mode, html] of Object.entries(documents)) {
      await writeFile(path.join(evidence, `${mode}.html`), html, "utf8");
    }

    const server = createServer((request, response) => {
      const mode = (request.url ?? "").includes("render") ? "render" : "preview";
      response.writeHead(200, { "content-type": "text/html; charset=utf-8" });
      response.end(documents[mode]);
    });
    await new Promise<void>((resolve) => server.listen(0, "127.0.0.1", resolve));
    const address = server.address();
    if (!address || typeof address === "string") throw new Error("parity harness reserved no port");

    const puppeteer = await import("puppeteer-core");
    let browser: Browser | null = null;
    try {
      browser = await puppeteer.launch({
        executablePath: available.chromePath,
        headless: true,
        args: ["--no-sandbox", "--disable-dev-shm-usage"],
      });
      const observed: Record<string, Array<string | null>> = { preview: [], render: [] };
      for (const mode of ["preview", "render"] as const) {
        const page = await browser.newPage();
        await page.goto(`http://127.0.0.1:${address.port}/${mode}`, { waitUntil: "domcontentloaded" });
        for (const point of POINTS) {
          observed[mode]!.push(await activeWordAt(page, point.sceneSeconds, 30));
        }
        await page.close();
      }
      // Printed as well as written: the evidence directory is temporary, and the
      // three observations are the whole result.
      process.stdout.write(`R6.14 caption parity ${JSON.stringify(observed)}\n`);
      await writeFile(
        path.join(evidence, "parity.json"),
        `${JSON.stringify({ points: POINTS, observed }, null, 2)}\n`,
        "utf8",
      );

      // The two documents agree with each other, and with what the timings say.
      expect(observed.render).toEqual(observed.preview);
      expect(observed.preview).toEqual(POINTS.map((point) => point.expect));
      // Both documents carry the same caption block, generated once from the
      // narration; a parity that held only because both were empty would not.
      expect(documents.render).toContain(">hai<");
      expect(documents.preview).toContain(">hai<");
    } finally {
      await browser?.close().catch(() => undefined);
      await new Promise<void>((resolve) => server.close(() => resolve()));
    }
  }, 180_000);
});
