import type {
  ColorPaletteDto,
  ColorPaletteHarmony,
  ColorPaletteId,
  ColorPaletteMood,
} from "@vidcom/contracts";

type PaletteResearch = Pick<ColorPaletteDto, "colorStory" | "guidance" | "source">;

function researched(
  code: string,
  swatches: [string, string, string, string],
  moods: ColorPaletteMood[],
  harmony: ColorPaletteHarmony,
  temperature: "cool" | "neutral" | "warm" | "mixed",
  energy: "calm" | "balanced" | "energetic",
  colorStory: string,
  chooseWhen: string,
  avoidWhen: string,
): PaletteResearch {
  return {
    colorStory,
    guidance: { moods, harmony, temperature, energy, chooseWhen, avoidWhen },
    source: {
      provider: "color-hunt",
      url: `https://colorhunt.co/palette/${code}`,
      swatches,
    },
  };
}

/** Source-backed creative guidance for every bundled palette. */
export const COLOR_PALETTE_RESEARCH: Readonly<Record<ColorPaletteId, PaletteResearch>> = {
  "clean-slate": researched("f9f7f7dbe2ef3f72af112d4e", ["#F9F7F7", "#DBE2EF", "#3F72AF", "#112D4E"],
    ["clean", "trustworthy", "calm", "understated"], "monochromatic", "cool", "calm",
    "Soft white and mist blue make room for content; clear blue signals action while navy carries readable authority.",
    "Choose for a neutral default, product walkthrough, or factual explainer with no stronger brand direction.",
    "Avoid when the brief asks for heat, celebration, urgency, or a deliberately cinematic dark world."),
  ocean: researched("e3f2fd90caf92196f30d47a1", ["#E3F2FD", "#90CAF9", "#2196F3", "#0D47A1"],
    ["trustworthy", "calm", "fresh"], "monochromatic", "cool", "calm",
    "A pale-water background rises through sky blue to saturated blue and deep navy, producing calm with a clear technical focus.",
    "Choose for technology, science, healthcare, finance, or any message that should feel reliable and composed.",
    "Avoid when the story needs warmth, appetite, handmade character, or immediate alarm."),
  forest: researched("e8f5e9a5d6a766bb6a1b5e20", ["#E8F5E9", "#A5D6A7", "#66BB6A", "#1B5E20"],
    ["natural", "calm", "grounded"], "monochromatic", "cool", "calm",
    "Airy mint and leaf green establish growth, while deep forest green grounds text and evidence.",
    "Choose for sustainability, wellness, agriculture, healthy growth, or steady long-term progress.",
    "Avoid when the subject is luxury nightlife, cyberpunk, or high-velocity disruption."),
  lavender: researched("f8b2b2af719d8b639b403d88", ["#F8B2B2", "#AF719D", "#8B639B", "#403D88"],
    ["gentle", "calm", "romantic"], "analogous", "mixed", "calm",
    "Blush, mauve, and lavender flow into an indigo anchor, creating softness without losing readable depth.",
    "Choose for wellness, thoughtful education, personal reflection, beauty, or calm creative products.",
    "Avoid when the message must feel hard-edged, clinical, urgent, or strictly institutional."),
  sunset: researched("5e244eaa1c41e68457ffe8b4", ["#5E244E", "#AA1C41", "#E68457", "#FFE8B4"],
    ["energetic", "dramatic", "romantic"], "analogous", "warm", "energetic",
    "Plum and crimson build dramatic depth; coral and warm cream deliver a glowing sunset payoff.",
    "Choose for launches, event recaps, transformation stories, lifestyle campaigns, or emotional calls to action.",
    "Avoid for conservative reporting, clinical instructions, or long text-heavy scenes that need visual quiet."),
  candy: researched("92003af62477ffadeeffe185", ["#92003A", "#F62477", "#FFADEE", "#FFE185"],
    ["playful", "energetic", "romantic"], "analogous", "warm", "energetic",
    "Berry red and vivid pink pop against candy pink and lemon, producing a sweet, social-first burst of energy.",
    "Choose for beauty, youth culture, celebrations, playful social video, or expressive community stories.",
    "Avoid for legal, financial, medical, or other contexts where playful sweetness weakens authority."),
  electric: researched("362f4f5b23ff008bffe4ff30", ["#362F4F", "#5B23FF", "#008BFF", "#E4FF30"],
    ["energetic", "innovative", "futuristic"], "complementary", "mixed", "energetic",
    "Deep violet supports electric indigo and blue, while acid lime creates a high-voltage focal accent.",
    "Choose for AI, gaming, innovation, sports technology, or a fast product reveal that must feel new.",
    "Avoid for wellness, heritage, mourning, or any brief asking for restraint and softness."),
  tropical: researched("321e4843637e65dcd5d9fff4", ["#321E48", "#43637E", "#65DCD5", "#D9FFF4"],
    ["fresh", "playful", "innovative"], "split-complementary", "cool", "balanced",
    "Aubergine and slate supply depth beneath bright aqua and mint, balancing freshness with digital polish.",
    "Choose for travel, hospitality, community, climate technology, or optimistic contemporary storytelling.",
    "Avoid when the brief needs earthy warmth, archival history, or severe monochrome authority."),
  midnight: researched("222831393e4600adb5eeeeee", ["#222831", "#393E46", "#00ADB5", "#EEEEEE"],
    ["premium", "dramatic", "futuristic"], "accented-neutral", "cool", "balanced",
    "Charcoal and graphite create cinematic depth; cyan provides precise digital highlights against cool white.",
    "Choose for premium technology, cinematic explainers, keynotes, dashboards, or nocturnal atmospheres.",
    "Avoid when the video should feel sunny, handcrafted, childlike, or emotionally warm."),
  noir: researched("0000001f150c412d15e1dcc9", ["#000000", "#1F150C", "#412D15", "#E1DCC9"],
    ["premium", "dramatic", "authoritative"], "accented-neutral", "warm", "calm",
    "Black and espresso brown form a restrained stage, with parchment as the elegant readable highlight.",
    "Choose for luxury, film, premium craft, serious profiles, or a reveal built on shadow and restraint.",
    "Avoid for dense educational diagrams, cheerful youth content, or interfaces needing many status colors."),
  cyber: researched("0000009929eaff5fcffaeb92", ["#000000", "#9929EA", "#FF5FCF", "#FAEB92"],
    ["futuristic", "innovative", "energetic"], "triadic", "mixed", "energetic",
    "Pure black carries neon violet and magenta, while pale yellow provides the readable signal layer.",
    "Choose for cybersecurity, gaming, virtual worlds, music visuals, or deliberately synthetic energy.",
    "Avoid for natural products, conservative institutions, or long-form calm explanation."),
  ember: researched("0f3040464858a56f63d99b7f", ["#0F3040", "#464858", "#A56F63", "#D99B7F"],
    ["urgent", "dramatic", "energetic"], "complementary", "mixed", "energetic",
    "Deep blue-black contains smoky slate and ember orange, creating controlled heat rather than raw alarm red.",
    "Choose for transformation, resilience, incident stories, sport, or urgency that still needs sophistication.",
    "Avoid when the message should feel innocent, airy, celebratory, or clinically neutral."),
  newsroom: researched("d90000ffea938db355000000", ["#D90000", "#FFEA93", "#8DB355", "#000000"],
    ["authoritative", "urgent", "trustworthy"], "triadic", "mixed", "energetic",
    "Signal red and black establish headline authority; muted green and paper yellow support data and context.",
    "Choose for breaking news, factual reports, scoreboards, public alerts, or evidence-led editorial video.",
    "Avoid for meditative wellness, romance, or premium minimalism where red reads as unnecessary alarm."),
  vintage: researched("2e29102c5745ebe3a7eb7d00", ["#2E2910", "#2C5745", "#EBE3A7", "#EB7D00"],
    ["nostalgic", "grounded", "handcrafted"], "complementary", "warm", "balanced",
    "Olive-black and heritage green sit beneath aged paper and burnt orange, suggesting print, archive, and patina.",
    "Choose for history, documentary, food heritage, craft, travel memory, or a retro editorial voice.",
    "Avoid for futuristic UI, clinical technology, or a pristine contemporary brand system."),
  monograph: researched("2c2c2c853953612d53f3f4f4", ["#2C2C2C", "#853953", "#612D53", "#F3F4F4"],
    ["understated", "authoritative", "premium"], "accented-neutral", "neutral", "calm",
    "Near-black and off-white keep typography dominant, while two wine accents add editorial personality.",
    "Choose for portfolios, architecture, essays, premium reports, or composition driven by type and whitespace.",
    "Avoid for playful children content, nature stories, or scenes that require many vivid categorical colors."),
  academia: researched("0b1849124d1ce4b028ebede3", ["#0B1849", "#124D1C", "#E4B028", "#EBEDE3"],
    ["intellectual", "authoritative", "trustworthy"], "triadic", "mixed", "balanced",
    "Ink navy and library green provide institutional weight; ochre marks evidence over a quiet paper field.",
    "Choose for research, education, museums, institutions, analysis, or historically grounded expertise.",
    "Avoid when the video needs casual spontaneity, neon futurism, or romantic softness."),
  terracotta: researched("524646a8a492fcf2e5ec5b38", ["#524646", "#A8A492", "#FCF2E5", "#EC5B38"],
    ["handcrafted", "grounded", "natural"], "accented-neutral", "warm", "balanced",
    "Charcoal brown and stone neutral support a cream canvas, with terracotta delivering a human, tactile accent.",
    "Choose for food, interiors, craft, architecture, local business, or human-centered product stories.",
    "Avoid for cyber, space, cold finance, or messages demanding immediate emergency intensity."),
  sand: researched("f7f1deb0ba999d66384e220f", ["#F7F1DE", "#B0BA99", "#9D6638", "#4E220F"],
    ["understated", "calm", "premium"], "analogous", "warm", "calm",
    "Warm ivory and sage create quiet space; ochre and espresso add grounded premium contrast.",
    "Choose for consulting, hospitality, understated luxury, slow living, or calm product explanation.",
    "Avoid for high-energy entertainment, urgent alerts, or bright youth-oriented campaigns."),
  rose: researched("fff1d3ffb090ca59955d1c6a", ["#FFF1D3", "#FFB090", "#CA5995", "#5D1C6A"],
    ["romantic", "gentle", "playful"], "analogous", "warm", "balanced",
    "Cream and peach soften expressive rose, while plum gives the palette enough depth for readable emotion.",
    "Choose for personal stories, beauty, relationships, community, celebrations, or emotionally warm narration.",
    "Avoid for emergency response, hard technical authority, or severe monochrome editorial work."),
  wheat: researched("133458838921d99b21faf7bb", ["#133458", "#838921", "#D99B21", "#FAF7BB"],
    ["grounded", "natural", "trustworthy"], "triadic", "mixed", "balanced",
    "Deep blue steadies olive and harvest gold, while pale wheat keeps the frame open and readable.",
    "Choose for agriculture, natural products, tradition, regional stories, or dependable practical guidance.",
    "Avoid for neon nightlife, romantic beauty, or stark black-and-white sophistication."),
};
