import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePaths = [
  "AGENTS.md",
  "skills/vidcom/SKILL.md",
  "skills/vidcom-project/SKILL.md",
  "skills/vidcom-scene/SKILL.md",
  "skills/vidcom-look/SKILL.md",
  "skills/vidcom-motion/SKILL.md",
  "skills/vidcom-narration/SKILL.md",
  "skills/vidcom-render/SKILL.md",
  "skills/vidcom-fix/SKILL.md",
  "skills/vidcom/agents/openai.yaml",
  "skills/vidcom-project/agents/openai.yaml",
  "skills/vidcom-scene/agents/openai.yaml",
  "skills/vidcom-look/agents/openai.yaml",
  "skills/vidcom-motion/agents/openai.yaml",
  "skills/vidcom-narration/agents/openai.yaml",
  "skills/vidcom-render/agents/openai.yaml",
  "skills/vidcom-fix/agents/openai.yaml",
  "prompts/create-video.md",
];
// Bumping this means every installed copy reports `outdated` and needs an
// explicit replace, so it moves only when the kit's contract really changes.
const version = 2;
const hash = (content) => `sha256:${createHash("sha256").update(content).digest("hex")}`;
const files = {};
for (const path of sourcePaths) files[path] = await readFile(join(root, path), "utf8");

// The marker inside each shipped file is what the installer classifies against.
// A file left behind at the old number would install as `outdated` forever, so
// the mismatch fails the build instead of shipping.
for (const [path, content] of Object.entries(files)) {
  const marker = /(?:^|\n)(?:(?:<!--|#)\s*)?x-vidcom-agent-kit:\s*(\d+)/u.exec(content)?.[1];
  if (marker === undefined) throw new Error(`${path} has no x-vidcom-agent-kit marker`);
  if (Number(marker) !== version) {
    throw new Error(`${path} is marked x-vidcom-agent-kit: ${marker} but the kit is version ${version}`);
  }
}
files["CLAUDE.md"] = files["AGENTS.md"];
await writeFile(join(root, "CLAUDE.md"), files["AGENTS.md"]);
const entries = Object.fromEntries(Object.entries(files).map(([path, content]) => [path, { content, contentHash: hash(content) }]));
const output = `// Generated by packages/agent-kit/scripts/build.mjs. Do not edit.\nexport const AGENT_KIT_VERSION = ${version} as const;\nexport const AGENT_KIT_FILES = ${JSON.stringify(entries, null, 2)} as const;\n`;
const target = join(root, "src/generated-bundle.ts");
await mkdir(dirname(target), { recursive: true });
await writeFile(target, output);
process.stdout.write(`generated ${relative(process.cwd(), target)}\n`);
