import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sourcePaths = [
  "AGENTS.md",
  "skills/vidcom/SKILL.md",
  "skills/vidcom-project/SKILL.md",
  "skills/vidcom-scene/SKILL.md",
  "skills/vidcom-look/SKILL.md",
  "skills/vidcom-narration/SKILL.md",
  "skills/vidcom-render/SKILL.md",
  "skills/vidcom-fix/SKILL.md",
  "skills/vidcom/agents/openai.yaml",
  "skills/vidcom-project/agents/openai.yaml",
  "skills/vidcom-scene/agents/openai.yaml",
  "skills/vidcom-look/agents/openai.yaml",
  "skills/vidcom-narration/agents/openai.yaml",
  "skills/vidcom-render/agents/openai.yaml",
  "skills/vidcom-fix/agents/openai.yaml",
  "prompts/create-video.md",
];
const hash = (content) => `sha256:${createHash("sha256").update(content).digest("hex")}`;
const files = {};
for (const path of sourcePaths) files[path] = await readFile(join(root, path), "utf8");
files["CLAUDE.md"] = files["AGENTS.md"];
await writeFile(join(root, "CLAUDE.md"), files["AGENTS.md"]);
const entries = Object.fromEntries(Object.entries(files).map(([path, content]) => [path, { content, contentHash: hash(content) }]));
const output = `// Generated by packages/agent-kit/scripts/build.mjs. Do not edit.\nexport const AGENT_KIT_VERSION = 1 as const;\nexport const AGENT_KIT_FILES = ${JSON.stringify(entries, null, 2)} as const;\n`;
const target = join(root, "src/generated-bundle.ts");
await mkdir(dirname(target), { recursive: true });
await writeFile(target, output);
process.stdout.write(`generated ${relative(process.cwd(), target)}\n`);
